language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
jdk:
  - oraclejdk8
before_install:
  - openssl aes-256-cbc -K $encrypted_ad238d7f4dc5_key -iv $encrypted_ad238d7f4dc5_iv -in secrets.tar.enc -out secrets.tar -d
  - tar -xvf secrets.tar --overwrite
  - chmod +x gradlew
script:
  - if [ "$TRAVIS_TAG" != "" ]; then ./gradlew publish; else ./gradlew build; fi
before_deploy:
  - export RELEASE_VERSION=$TRAVIS_TAG
  - export RELEASE_CHANGELOG=$(cat app/src/main/play/release-notes/en-US/default.txt)
  - export RELEASE_FILE="app/build/outputs/apk/*/*.apk"
deploy:
  - provider: script
    skip_cleanup: true
    script: bash ./.scripts/deploy.sh
    on:
      branch: master
      tags: true
  - provider: releases
    api_key: "${GITHUB_TOKEN}"
    skip_cleanup: true
    overwrite: true
    file_glob: true
    file: "${RELEASE_FILE}"
    tag_name: "${RELEASE_VERSION}"
    on:
      branch: master
      tags: true
