name: trigger gitlab job
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger Job
      uses: ridd0053/Asteroid@feature_branch_pipeline
      with:
        url: "http://example.com"
        token: ${{ secrets.TOKEN }}
        project_id: 100