Name: Build

on:
  push:
    branches:
    - feature_branch_pipeline
stages:
  - build
  - test

jobs:
  build:
    stage: build
     script:
      - echo "Building"
      - mkdir build
      - touch build/info.txt

      artifacts:
        paths:
         - build/
  test:
    stage: test
    script:
      - echo "Testing"
      - test -f "build/info.txt"
